-- All SQL QUERIES

-- Q1
SELECT CUSTOMER, MARKET FROM DIM_CUSTOMER
WHERE CUSTOMER = "ATLIQ EXCLUSIVE" AND 
REGION = "APAC"

-- Q2
WITH FISCAL_YEAR_2020 AS (
SELECT COUNT(DISTINCT PRODUCT_CODE) AS 2020_UNIQUE_PRODUCTS FROM FACT_SALES_MONTHLY
WHERE FISCAL_YEAR = 2020
),
FISCAL_YEAR_2021 AS (
SELECT COUNT(DISTINCT PRODUCT_CODE) AS 2021_UNIQUE_PRODUCTS FROM FACT_SALES_MONTHLY
WHERE FISCAL_YEAR = 2021)
SELECT 2020_UNIQUE_PRODUCTS, 2021_UNIQUE_PRODUCTS,
CONCAT(ROUND(((2021_UNIQUE_PRODUCTS-2020_UNIQUE_PRODUCTS)/2020_UNIQUE_PRODUCTS)*100,2), "%") AS PCT_CHG
FROM FISCAL_YEAR_2020, FISCAL_YEAR_2021

-- Q3
SELECT SEGMENT, COUNT(DISTINCT PRODUCT_CODE) AS PRODUCT_CNT
FROM DIM_PRODUCT
GROUP BY SEGMENT
ORDER BY PRODUCT_CNT DESC

-- Q4
WITH X AS(
SELECT SEGMENT, COUNT(DISTINCT P.PRODUCT_CODE) AS PRODUCT_CNT_FOR_20
FROM DIM_PRODUCT P
JOIN FACT_SALES_MONTHLY S ON 
P.PRODUCT_CODE = S.PRODUCT_CODE
WHERE FISCAL_YEAR = 2020
GROUP BY SEGMENT),
Y AS(
SELECT SEGMENT, COUNT(DISTINCT P.PRODUCT_CODE) AS PRODUCT_CNT_FOR_21
FROM DIM_PRODUCT P
JOIN FACT_SALES_MONTHLY S ON 
P.PRODUCT_CODE = S.PRODUCT_CODE
WHERE FISCAL_YEAR = 2021
GROUP BY SEGMENT)
SELECT X.SEGMENT, PRODUCT_CNT_FOR_20, PRODUCT_CNT_FOR_21, (PRODUCT_CNT_FOR_21 - PRODUCT_CNT_FOR_20) AS DIFF
FROM X JOIN Y ON X.SEGMENT = Y.SEGMENT ORDER BY DIFF

-- Q5
WITH MAX_COST AS(
SELECT P.PRODUCT_CODE, P.PRODUCT, M.MANUFACTURING_COST
FROM DIM_PRODUCT P
JOIN FACT_MANUFACTURING_COST M
ON P.PRODUCT_CODE = M.PRODUCT_CODE
WHERE M.MANUFACTURING_COST = (SELECT MAX(MANUFACTURING_COST) FROM FACT_MANUFACTURING_COST)),
MIN_COST AS (
SELECT P.PRODUCT_CODE, P.PRODUCT, M.MANUFACTURING_COST
FROM DIM_PRODUCT P
JOIN FACT_MANUFACTURING_COST M
ON P.PRODUCT_CODE = M.PRODUCT_CODE
WHERE M.MANUFACTURING_COST = (SELECT MIN(MANUFACTURING_COST) FROM FACT_MANUFACTURING_COST))
SELECT * FROM MAX_COST
UNION 
SELECT * FROM MIN_COST

-- Q6
SELECT C.CUSTOMER, C.CUSTOMER_CODE, CONCAT(ROUND(AVG(P.PRE_INVOICE_DISCOUNT_PCT*100),2),"%") AS AVERAGE_DISCOUNT_PERCENTAGE
FROM FACT_PRE_INVOICE_DEDUCTIONS P
JOIN DIM_CUSTOMER C ON
P.CUSTOMER_CODE = C.CUSTOMER_CODE
WHERE C.MARKET = "INDIA" AND P.FISCAL_YEAR = 2021
GROUP BY C.CUSTOMER, C.CUSTOMER_CODE
ORDER BY AVG(P.PRE_INVOICE_DISCOUNT_PCT*100) DESC
LIMIT 5

-- Q7
SELECT MONTHNAME(S.DATE) AS MONTH, S.FISCAL_YEAR, CONCAT(ROUND(SUM((S.SOLD_QUANTITY*P.GROSS_PRICE))/1000000,2)," M") AS GROSS_SALES
FROM DIM_CUSTOMER C
JOIN FACT_SALES_MONTHLY S
ON C.CUSTOMER_CODE = S.CUSTOMER_CODE
JOIN FACT_GROSS_PRICE P
ON S.PRODUCT_CODE = P.PRODUCT_CODE
WHERE C.CUSTOMER = "ATLIQ EXCLUSIVE"
GROUP BY MONTHNAME(S.DATE),S.FISCAL_YEAR
ORDER BY S.FISCAL_YEAR

-- Q8
SELECT 
CASE
    WHEN MONTH(DATE) IN (9,10,11) THEN "Q1" 
	WHEN MONTH(DATE) IN (12,01,02) THEN "Q2"
	WHEN MONTH(DATE) IN (03,04,05) THEN "Q3"
    WHEN MONTH(DATE) IN (06,07,08) THEN "Q4"
    END AS QUARTERS,
    CONCAT(ROUND(SUM(SOLD_QUANTITY)/1000000,2), " M")  AS TOTAL_SOLD_QUANTITY
FROM FACT_SALES_MONTHLY
WHERE FISCAL_YEAR = 2020
GROUP BY QUARTERS
ORDER BY TOTAL_SOLD_QUANTITY DESC

-- Q9
WITH X AS (SELECT C.CHANNEL,
ROUND(SUM(G.GROSS_PRICE*S.SOLD_QUANTITY)/100000,2) AS GROSS_SALES_MLN
FROM FACT_SALES_MONTHLY S
JOIN DIM_CUSTOMER C USING(CUSTOMER_CODE)
JOIN FACT_GROSS_PRICE G USING(PRODUCT_CODE)
WHERE S.FISCAL_YEAR=2021
GROUP BY C.CHANNEL)
SELECT CHANNEL, GROSS_SALES_MLN,
ROUND((GROSS_SALES_MLN/(SELECT SUM(GROSS_SALES_MLN) FROM X))*100,2)
 AS PCT FROM X
ORDER BY GROSS_SALES_MLN DESC;

-- Q10
 WITH X AS
(
SELECT P.DIVISION, S.PRODUCT_CODE, P.PRODUCT, CONCAT(ROUND(SUM(S.SOLD_QUANTITY)/1000000,2), " M") AS TOTAL_SOLD_QUANTITY,
DENSE_RANK() OVER(PARTITION BY P.DIVISION ORDER BY SUM(S.SOLD_QUANTITY) DESC) AS 'RANK_ORDER'
FROM DIM_PRODUCT P JOIN FACT_SALES_MONTHLY S
ON P.PRODUCT_CODE = S.PRODUCT_CODE
WHERE S.FISCAL_YEAR = 2021
GROUP BY P.DIVISION, S.PRODUCT_CODE, P.PRODUCT)
 SELECT * FROM X
WHERE RANK_ORDER <= 3
ORDER BY DIVISION, RANK_ORDER; 